- docker-langserver/Dockerfile
- lua-language-server/Dockerfile
> #1: Adds docker and lua language servers

- .env
- bash-language-server/Dockerfile
- build.sh
- docker-compose.yml
- docker-langserver/Dockerfile
- go-language-server/Dockerfile
- gopls/Dockerfile
- lua-language-server/Dockerfile
- node_base/Dockerfile
- typescript-language-server/Dockerfile
- yaml-language-server/Dockerfile
> #8: Changes from issue #6

- pyright/Dockerfile
Adds support for [pyright](https://github.com/Microsoft/pyright)
> Add pyright

- docker-compose.yml
- rust-analyzer/Dockerfile
Add rust-analyzer to support Rust
> feat(rust): Add rust language server

- .github/workflows/build-image.yml
> #14: Implements Github Action for bashls server

- .github/workflows/build-image.yml
> #18: Implements build matrix and rest of LSP jobs

- .github/workflows/build-image.yml
> #20: Adds build-args to Github Actions

- .env
- docker-compose.yaml
- servers/sveltels/Dockerfile
- servers/svelteserver/Dockerfile
Hi, this is my fist PR to any project so I'm sorry if I'm doing some basics wrong.
I tried to add the svelte server exactly like the others and tested it by adding "additional_languages" in my lspcontainers.nvim config. It is working for me. I can also create a PR on the lspcontainers.nvim repo to add svelte to the supported languages.
> Svelte language server

- .env
- .github/workflows/build-image.yml
- docker-compose.yaml
- servers/html/Dockerfile
> feature: adding html language server

- .env
- .github/workflows/build-image.yml
- docker-compose.yaml
- servers/vuels/Dockerfile
> feature: adding Vue Language Server

- .env
- .github/workflows/build-image.yml
> feature: terraformls 0.17

- servers/pylsp/Dockerfile
I think in the process of reducing the container size, I forgot to add
the install command. Whoops!
> pylsp: Install python3 inside the 2nd container stage

- .env
- .github/workflows/build-image.yml
- docker-compose.yaml
- servers/intelephense/Dockerfile
This MR adds the [intelephense php language server](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#intelephense).
See the lspcontainers.nvim PR: https://github.com/lspcontainers/lspcontainers.nvim/pull/28
I have tested it with my lspcontainers.nvim fork locally.
> feature: adding intelephense

- .env
- .github/workflows/build-image.yml
- docker-compose.yaml
- servers/clangd/Dockerfile
I've added clangd language server, based on other Dockerfiles inside this repository. However, since this is separate from lspcontainers.nvim repository, I'm not sure how to test it properly. It'd be great if I you could give me some pointers on that ;)
> Add clangd language server

- .github/workflows/build-image.yml
- servers/powershell_es/Dockerfile
- Adds `powershell_es` to build workflow
- Uses `alpine` base image for `powershell_es`
> feat(workflow): add powershell_es

- .github/workflows/build-image.yml
- docker-compose.yaml
- servers/graphql-lsp/Dockerfile
> Add graphql-lsp

- .github/workflows/build-image.yml
- docker-compose.yaml
- servers/prisma/Dockerfile
> Add Prisma Language Server

- servers/tailwindcss/Dockerfile
Adds [tailwindcss language server](https://github.com/tailwindlabs/tailwindcss-intellisense/tree/master/packages/tailwindcss-language-server).
> feat: add tailwindcss

- servers/jsonls/Dockerfile
as of the instructions on:
https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#jsonls
> update npm packaga and entrycmd

- .github/workflows/build-image.yml
Add a cron schedule for the `build_and_push` job.
Closes #69 (nice)
> feat(ci): add nightly job

- servers/powershell_es/Dockerfile
> update release version 2.5.1 > 3.4.8

- servers/gopls/Dockerfile
- servers/gopls/docker_entrypoint.sh
Similiar to #83 - we have a common problem with some language servers which is they require the file system to read and or write data which includes permissions.
To try and improve on this - I have simplified the `docker_entrypoint.sh` to only focus on updating the user and silently fail if the group can't update. I have also standardized language server images to use the same user and commands.
> Improve gopls Dockerfile
